spring:

  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5438/paymentdb
    username: paymentuser
    password: paymentpass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: liquibase/changelog-master.yml
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all

    consumer:
      group-id: payment-service-orch-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        enable.auto.commit: false

    listener:
      ack-mode: manual

server:
  port: 8082

payment:
  retry:
    max-attempts: 3
    delay-ms: 2000

logging:
  level:
    com.saga.payment: DEBUG